version: 2
jobs:
  build_test_image:
    machine: true
    context: build
    steps:
      - checkout
      - run: |
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          make push_test_image
  test:
    docker:
      - image: saturncloud/sutils-test
    steps:
      - checkout
      - run: |
          export PATH=/opt/conda/bin:${PATH}
          make test
  package:
    docker:
      - image: saturncloud/sutils-test
    context: build
    steps:
      - checkout
      - run: |
          export PATH=/opt/conda/bin:${PATH}
          export CONDA_OUTPUT=/tmp/output
          make package
workflows:
  version: 2
  build_test_image:
    jobs:
      - build_test_image:
          context: build
          filters:
            tags:
              only: /^test-image.*/
            branches:
              ignore: /.*/
  test:
    jobs:
      - test:
          context: build
  package:
    jobs:
      - test:
          context: build
          filters:
            tags:
              only: /^prod.*/
            branches:
              ignore: /.*/
      - package:
          requires:
            - test
          context: build
          filters:
            tags:
              only: /^prod.*/
            branches:
              ignore: /.*/
