version: 2
jobs:
  build_image:
    machine: true
    context: docker_hub
    steps:
      - checkout
      - run: |
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          echo "CONTEXT: ${DOCKER_USER},  ${DOCKER_PASS}"
workflows:
  version: 2
  build_image:
    jobs:
      - hold_for_approval:
          type: approval
      - build_image:
          context: docker_hub
          requires:
            - hold_for_approval
