version: 2
jobs:
  build_image:
    machine: true
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          make test_image
workflows:
  version: 2
  build_image:
    jobs:
      - build_image:
          context: docker_hub
