version: 2
jobs:
  build_test_image:
    machine: true
    context: build
    steps:
      - checkout
      - run: |
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          make push_test_image
  test:
    docker:
      - image: saturncloud/sutils-test
    steps:
      - checkout
      - run: |
          echo 'export PATH=/opt/conda/bin:${PATH}' >> $BASH_ENV
          source /home/circleci/.bashrc
      - run: |
          make test
  dev_package:
    docker:
      - image: saturncloud/sutils-test
    context: build
    environment:
      PATH: "/opt/conda/bin:${PATH}"
    steps:
      - checkout
      - run: |
          echo 'export PATH=/opt/conda/bin:${PATH}' >> $BASH_ENV
          source /home/circleci/.bashrc
      - run: |
          make dev_package
workflows:
  version: 2
  build_test_image:
    jobs:
      - hold_for_approval:
          type: approval
      - build_test_image:
          context: build
          requires:
            - hold_for_approval
  test_and_package:
    jobs:
      - test:
          context: build
      - dev_package:
          context: build
          requires:
            - test
