version: 2
jobs:
  build_image:
    machine: true
    context: docker_hub
    steps:
      - checkout
      - run: |
          echo "CONTEXT: ${DOCKER_USER},  ${DOCKER_PASS}"
workflows:
  version: 2
  build_image:
    jobs:
      - build_image:
          context: docker_hub
